name: 'Tag With Aliases'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  aliases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haya14busa/action-update-semver@v1
