name: "tests"

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all
  assert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: major
        uses: ./
        with:
          version: "3.14.1"
          major: true
          minor: false
          patch: false

      - name: Major version is provided as alias
        uses: pr-mpt/actions-assert@v1
        with:
          assertion: npm://@assertions/is-equal
          expected: "v3.14"
          actual: "${{ steps.major.outputs.csv }}"

      - id: minor
        uses: ./
        with:
          version: "3.14.1"
          major: false
          minor: true
          patch: false

      - name: Minor version is provided as alias
        uses: pr-mpt/actions-assert@v1
        with:
          assertion: npm://@assertions/is-equal
          expected: "v3.14"
          actual: "${{ steps.minor.outputs.csv }}"

      - id: patch
        uses: ./
        with:
          version: "3.14.1"
          major: false
          minor: false
          patch: true

      - name: Patch version is provided as alias
        uses: pr-mpt/actions-assert@v1
        with:
          assertion: npm://@assertions/is-equal
          expected: "v3.14.1"
          actual: "${{ steps.patch.outputs.csv }}"

      - id: all
        uses: ./
        with:
          version: "3.14.1"
          major: true
          minor: true
          patch: true

      - name: All versions are provided as aliases
        uses: pr-mpt/actions-assert@v1
        with:
          assertion: npm://@assertions/is-equal
          expected: "v3,v3.14,v3.14.1"
          actual: "${{ steps.all.outputs.csv }}"

      - name: List provides new-line separated aliases
        uses: pr-mpt/actions-assert@v1
        with:
          assertion: npm://@assertions/is-equal
          expected: |
            v3
            v3.14
            v3.14.1
          actual: "${{ steps.all.outputs.list }}"

      - id: none
        uses: ./
        with:
          version: "3.14.1"
          major: false
          minor: false
          patch: false

      - name: No versions are provided as aliases
        uses: pr-mpt/actions-assert@v1
        with:
          assertion: npm://@assertions/is-equal
          expected: ""
          actual: "${{ steps.none.outputs.csv }}"

      - id: prefixed
        uses: ./
        with:
          version: "3.14.1"
          major: true
          minor: true
          patch: true

      - name: All versions are prefixed
        uses: pr-mpt/actions-assert@v1
        with:
          assertion: npm://@assertions/starts-with
          each: true
          expected: "v"
          actual: "${{ steps.prefixed.outputs.list }}"

